feat(ui-element): Add TextWithImageUiElement
monsieurbiz/SyliusUiElementsPlugin pull request #4
Opened 2024-08-06 09:27 UTC by welcoMattic

This PR adds a hard dependency to [SyliusMediaManagerPlugin](https://github.com/monsieurbiz/SyliusMediaManagerPlugin/), to be able to use the best `ImageType`.

# Admin form
![Screenshot 2024-08-06 at 11-12-37 Edit product Sylius](https://github.com/user-attachments/assets/c107e455-fb76-4453-8fbd-4bd68045b294)

# Admin preview
![Screenshot 2024-08-06 at 11-21-56 Edit product Sylius](https://github.com/user-attachments/assets/c6c020c6-6e0b-43d3-84c3-3cc75cb9d481)

2024-08-06 10:02 UTC, lanfisis requested changes

2024-08-06 10:02 UTC, lanfisis commented on src/Form/Type/UiElement/TextWithImageUiElementType.php
> +                    \sprintf('monsieurbiz_ui_elements.ui_element.text_with_image_ui_element.fields.image_align.choices.%s', self::IMAGE_POSITION_LEFT) => self::IMAGE_POSITION_LEFT,
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** ‏
```suggestion
                    \sprintf('%s.%s', self::IMAGE_POSITION_LABEL, self::IMAGE_POSITION_LEFT) => self::IMAGE_POSITION_LEFT,
```
Add const for better readability

2024-08-06 11:48 UTC, delyriand commented on src/Form/Type/ImageType.php
> +}
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** use the `getParent` method instead extends the RichEditorImageType class

‏
```suggestion
class ImageType extends AbstractType
{
    /**
     * @inheritdoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if (!$options['with_link']) {
            $builder->remove('link');
        }

        if (!$options['with_alignment']) {
            $builder->remove('align');
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'with_link' => true,
            'with_alignment' => true,
        ]);
        $resolver->setAllowedTypes('with_link', ['null', 'bool']);
        $resolver->setAllowedTypes('with_alignment', ['null', 'bool']);
    }
    
    public function getParent(): string
    {
        return RichEditorImageType::class;
    }
}
```

2024-08-06 13:20 UTC, delyriand approved these changes

2024-08-07 06:53 UTC, maximehuran commented on src/Form/Type/ImageType.php
> +class ImageType extends AbstractType
What is the use case of this class ?

2024-08-07 07:36 UTC, welcoMattic commented on src/Form/Type/ImageType.php
> +class ImageType extends AbstractType
In `TextWithImageUiElement`, we need an image field without link and alignment. However, the `ImageType` of RichEditor provide mandatory `link` and `alignment` fields. This child `ImageType` allow us to choose whether to have `link` and/or `alignment` fields.

2024-08-07 15:02 UTC, maximehuran approved these changes

2024-08-08 06:49 UTC, lanfisis approved these changes

2024-08-08 07:43 UTC, merged