fix(ui-element): Add missing LinksUiElement templates
monsieurbiz/SyliusUiElementsPlugin pull request #5
Opened 2024-08-06 12:39 UTC by welcoMattic

# Admin Form
![Screenshot 2024-08-06 at 14-37-46 Edit product Sylius](https://github.com/user-attachments/assets/e0f11f98-1ed7-453f-84ff-9b1c5112b65c)

# Admin Preview
![Screenshot 2024-08-06 at 14-37-40 Edit product Sylius](https://github.com/user-attachments/assets/069c0713-5ca7-4d18-8e01-01e5c82819cc)

2024-08-06 12:48 UTC, lanfisis approved these changes

2024-08-06 13:33 UTC, delyriand requested changes

2024-08-06 13:33 UTC, delyriand commented on src/Resources/views/Shop/UiElement/links_ui_element.html.twig
> +type: customer_quote_ui_element
<!-- Nitpicks are small, trivial, but necessary changes. Distinguishing nitpick comments significantly helps direct the reader's attention to comments requiring more involvement.  -->
**🤓 nitpick:** wrong type ‏

2024-08-06 13:33 UTC, delyriand commented on src/Resources/views/Shop/UiElement/links_ui_element.html.twig
> +        - type
<!-- Nitpicks are small, trivial, but necessary changes. Distinguishing nitpick comments significantly helps direct the reader's attention to comments requiring more involvement.  -->
**🤓 nitpick:** fields doesn't match with the content of element‏

2024-08-06 13:33 UTC, delyriand commented on src/Resources/views/Shop/UiElement/links_ui_element.html.twig
> +</div>
<!-- Issues represent user-facing problems. If possible, it's great to follow this kind of comment with a suggestion.  -->
**🔨 issue:** are you sure that template works? because in the LinksUiElementType i dont see description

2024-08-08 08:03 UTC, maximehuran requested changes

2024-08-08 08:03 UTC, maximehuran commented on src/Form/Type/UiElement/CustomerQuoteUiElementType.php
> +            ->add('link', UrlType::class, [
```suggestion
            ->add('link', TextType::class, [
```

It's better to use a TextType.
Link type force us to have a protocol etc...
You cannot add a relative link like `/page/cgv`

2024-08-08 11:27 UTC, delyriand requested changes
same comment as maxime

2024-08-09 08:51 UTC, welcoMattic commented on src/Form/Type/UiElement/CustomerQuoteUiElementType.php
> +            ->add('link', UrlType::class, [
I disagree, `UrlType` only provide the HTML attribute `inputmode` valued to `url` to open the right keyboard on mobile. The validation constraints are on us, and here we use `AtLeastOneOf` with `Url` and `Regex` to allow relative URLs. Check it out


https://github.com/user-attachments/assets/5dc578aa-3b25-485e-a823-ef874c7d0089

cc @delyriand

2024-08-09 08:53 UTC, delyriand approved these changes

2024-08-10 09:00 UTC, merged