feat(ui-element): Add TextWithImageUiElement
monsieurbiz/SyliusUiElementsPlugin pull request #6
Opened 2024-08-06 13:16 UTC by welcoMattic

# Admin Form
![Screenshot 2024-08-06 at 15-13-04 Edit product Sylius](https://github.com/user-attachments/assets/037c2c30-a2c2-4f57-8ff1-7e93b221e860)

# Admin Preview
![Screenshot 2024-08-06 at 15-12-50 Edit product Sylius](https://github.com/user-attachments/assets/92a13ee9-a20e-4bb8-a31a-03c36a878661)

2024-08-08 08:01 UTC, maximehuran commented on src/Form/Type/UiElement/LogosUiElementType.php
> +                    'class' => 'ui segment',
```suggestion
                    'class' => 'ui segment secondary collection--flex',
```

Can you add `collection--flex` class ? And `secondary` to have grey background.
The class `collection--flex` is not used in the test app, but in pagaio it will be displayed like this : 

![image](https://github.com/user-attachments/assets/002e4213-8d82-441d-addb-406815fd4f84)

https://github.com/monsieurbiz/SyliusCaseStudyPlugin/blob/master/src/Form/Type/UiElement/CaseStudyUiElementType.php#L56

2024-08-08 11:31 UTC, delyriand requested changes

2024-08-08 11:31 UTC, delyriand commented on src/Resources/views/Shop/UiElement/logos_ui_element.html.twig
> +                    <img src="{{ logo.image }}" alt="{{ logo.alt }}" title="{{ logo.title }}">
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** use a liip imagine filter to avoid huge image‏

2024-08-08 11:31 UTC, delyriand commented on src/Resources/views/Admin/UiElement/logos_ui_element.html.twig
> +                <img src="{{ logo.image }}" alt="{{ logo.alt }}" title="{{ logo.title }}" width="180">
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** add default value for `alt` and `title`, these fields are not mandatory‏

2024-08-08 11:31 UTC, delyriand commented on src/Resources/views/Admin/UiElement/logos_ui_element.html.twig
> +        <span class="ui huge header">{{ element.title }}</span>
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** add default and condition to the title, this field is not mandatory in your formtype‏

2024-08-08 11:31 UTC, delyriand commented on src/Resources/views/Shop/UiElement/logos_ui_element.html.twig
<!-- Chores are simple tasks that must be done before the subject can be “officially” accepted. Usually, these comments reference some common process. Try to leave a link to the process description so that the reader knows how to resolve the chore.  -->
**💣 chore:** same returns as in admin template‏

2024-08-09 08:56 UTC, welcoMattic commented on src/Resources/views/Shop/UiElement/logos_ui_element.html.twig
> +                    <img src="{{ logo.image }}" alt="{{ logo.alt }}" title="{{ logo.title }}">
Which one? A predefined in Sylius?

2024-08-09 08:58 UTC, delyriand commented on src/Resources/views/Shop/UiElement/logos_ui_element.html.twig
> +                    <img src="{{ logo.image }}" alt="{{ logo.alt }}" title="{{ logo.title }}">
or create one for this case `monsieurbiz_ui_element_logo`

2024-08-09 08:59 UTC, welcoMattic commented on src/Resources/views/Shop/UiElement/logos_ui_element.html.twig
> +                    <img src="{{ logo.image }}" alt="{{ logo.alt }}" title="{{ logo.title }}">
`sylius_medium` is about 'size: [240, 180]', looks good to me

2024-08-10 09:01 UTC, merged